server:
  port: 8901

spring:
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/, http://eurekaserver2:8762/eureka/

    register-with-eureka: true
    fetch-registry: true

#ESB URL
  
  