server:
  port: 8910


spring:
  application:
    name: stock-service

  zipkin:
      base-url: http://localhost:9411
      enabled: true

  sleuth:
      sampler:
        probability: 1.0


eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/, http://eurekaserver2:8762/eureka/

    register-with-eureka: true
    fetch-registry: true

